### ISSUE TITLE
java.io.FileNotFoundException: F:\Torus Regular.otf

### ISSUE THREAD

**Issue by linux-leo** [BloCamLimb/ModernUI#102]
**Describe the bug**
Why is modern UI trying to access my F:/ drive? Did I download Malware?

java.io.FileNotFoundException: F:\Torus Regular.otf (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at icyllis.modernui.text.Typeface.<clinit>(Typeface.java:77)
	at icyllis.modernui.forge.ModernUIForge.loadFonts(ModernUIForge.java:251)
	at icyllis.modernui.forge.ModernUIForge.getPreferredTypeface(ModernUIForge.java:218)
	at icyllis.modernui.forge.Config$Client.reload(Config.java:422)
	at icyllis.modernui.forge.Config.reload(Config.java:107)
	at icyllis.modernui.forge.Config$$Lambda$3453/0x0000000064587608.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3215/0x00000000574ad6c0.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3418/0x00000000574b89d8.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3367/0x00000000574fc438.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:152)
	at net.minecraftforge.fml.ModContainer$$Lambda$3958/0x0000000066181d58.accept(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:152)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:106)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$3911/0x0000000063ddb550.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83)
	at net.minecraftforge.fml.ModLoader.lambda$null$18(ModLoader.java:208)
	at net.minecraftforge.fml.ModLoader$$Lambda$3910/0x0000000063ddb3d0.run(Unknown Source)
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125)
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:208)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$7(ClientModLoader.java:132)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3904/0x0000000063dda848.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3201/0x0000000061b7c088.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:132)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:114)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3901/0x0000000063dd9ee8.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3201/0x0000000061b7c088.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**To Reproduce**

1. use this mod
2. launch minecraft

**Environment**
 - Mod Version: 1.16.5-2.7.0.104 (2022-04-23)
 - Forge Version: newest for 1.16.5
 - Operating System: windows 10

**Comment by linux-leo** [comment]
In core/src/main/java/icyllis/modernui/text/Typeface.java theres the following piece of code:

```
        try (InputStream stream = new FileInputStream("F:/Torus Regular.otf")) {
            Font font = Font.createFont(Font.TRUETYPE_FONT, stream);
            p.add(font);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
```
Maybe somebody could backport the 1.18 version of the file that doesnt include this?, or just remove it.

**Comment by BloCamLimb** [comment]
Just ignore it. It's just a few more lines of logs, not a bug.

**Comment by BloCamLimb** [comment]
Should be fixed in next minor update.
