### ISSUE TITLE
MacOs M1 OpenGL 4.6 

### ISSUE THREAD

**Issue by ThuShalil** [BloCamLimb/ModernUI#124]
version: 3.5.3.112
OS: MacOs 13.0 Beta, processor arm m1
java: zulu jdk 18 for arm64

Older version 3.5.2.111 working fine.

Error log: 
```[17:48:20] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:48:22] [pool-6-thread-1/INFO] [Simple RPC/]: Connected and Ready!
[17:48:33] [Render thread/WARN] [minecraft/Main]: Failed to create window: 
com.mojang.blaze3d.platform.Window$WindowInitFailed: GLFW error 65543: Requested OpenGL version 4.6, got version 4.1
	at com.mojang.blaze3d.platform.Window.m_85412_(Window.java:242) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinWindow,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1-mmachina.1.jar%232!/:SNAPSHOT] {}
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1-mmachina.1.jar%238!/:SNAPSHOT] {}
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1-mmachina.1.jar%232!/:SNAPSHOT] {re:mixin}
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1-mmachina.1.jar%232!/:SNAPSHOT] {re:mixin}
	at com.mojang.blaze3d.platform.Window.redirect$bpf000$onInit(Window.java:637) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinWindow,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:83) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinWindow,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:MinecraftClientMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:simplerpc.mixins.json:ScreenEventsMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}
```

![image](https://user-images.githubusercontent.com/1362581/185437846-02c97145-1cb5-44a4-90b1-fd80fa4bd4e8.png)

**Comment by BloCamLimb** [comment]
3.5.3 is an update especially for AMD's discrete GPUs, not for macOS. There are no feature additions or bug fixes.
