### ISSUE TITLE
Unable to launch on macOS: There is no OpenGL context current in the current thread.

### ISSUE THREAD

**Issue by ResetPower** [BloCamLimb/ModernUI#130]
Installed MoltenVK and Mesa 22.1.7 with Homebrew
JVM argument is `-Dorg.lwjgl.opengl.libname=/usr/local/Cellar/mesa/22.1.7_1/lib/libGL.1.dylib`

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-09-11 01:56:16
Description: Initializing game

java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:385) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:314) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:298) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at com.mojang.blaze3d.platform.Window.<init>(Window.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.25.jar%2395!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:385) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:314) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:298) ~[lwjgl-opengl-3.3.1.jar%23136!/:build 7] {re:mixin}
        at com.mojang.blaze3d.platform.Window.<init>(Window.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
        Modules: 
Stacktrace:
        at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.25.jar%2395!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
        Minecraft Version: 1.19.2
        Minecraft Version ID: 1.19.2
        Operating System: Mac OS X (x86_64) version 12.5.1
        Java Version: 17.0.4.1, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 436131184 bytes (415 MiB) / 687865856 bytes (656 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 12
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
        Identifier: Intel64 Family 6 Model 158 Stepping 10
        Microarchitecture: Coffee Lake
        Frequency (GHz): 2.60
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: Intel UHD Graphics 630
        Graphics card #0 vendor: Intel
        Graphics card #0 VRAM (MB): 1536.00
        Graphics card #0 deviceId: 0x3e9b
        Graphics card #0 versionInfo: Revision ID: 0x0000, gMux Version: 5.0.0
        Graphics card #1 name: Radeon Pro 555X
        Graphics card #1 vendor: AMD (0x1002)
        Graphics card #1 VRAM (MB): 4096.00
        Graphics card #1 deviceId: 0x67ef
        Graphics card #1 versionInfo: Revision ID: 0x00e3, ROM Revision: 113-C980AL-075, VBIOS Version: 113-C97501P-005, EFI Driver Version: 01.A1.075, gMux Version: 5.0.0
        Memory slot #0 capacity (MB): 8192.00
        Memory slot #0 clockSpeed (GHz): 2.40
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MB): 8192.00
        Memory slot #1 clockSpeed (GHz): 2.40
        Memory slot #1 type: DDR4
        Virtual memory max (MB): 17408.00
        Virtual memory used (MB): 9199.64
        Swap memory total (MB): 1024.00
        Swap memory used (MB): 2.00
        JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx4096m
        Launched Version: 1.19.2-forge-43.1.25
        Backend library: LWJGL version 3.3.1 build 7
        Backend API: Unknown
        Window size: <not initialized>
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'forge'
        Type: Client (map_client.txt)
        CPU: <unknown>
```

**Comment by r58Playz** [comment]
GLFW needs to be patched to use mesa.

(Or go look at https://github.com/r58Playz/mglmod - in progress)

**Comment by ResetPower** [comment]
mglmod seems like a fabric mod, can it work with Modern UI?

**Comment by BloCamLimb** [comment]
Can you also post the debug.log?

**Comment by ResetPower** [comment]
where should i find it 🤔

**Comment by BloCamLimb** [comment]
Your console output, located at `[gamedir]/logs/debug.log`. I can run the game with mesa zink on Windows without patching.

**Comment by ResetPower** [comment]
```
[11:45:25] [main/INFO]: ModLauncher running: args [--username, ResetPower, --version, 1.19.2-forge-43.1.25, --gameDir, /Users/resetpower/Library/Application Support/epherome/minecraft, --assetsDir, /Users/resetpower/Library/Application Support/epherome/minecraft/assets, --assetIndex, 1.19, --uuid, d9876a2d14694b86859d902f267067d6, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3.222, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.25, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[11:45:25] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4.1 by Oracle Corporation; OS Mac OS X arch x86_64 version 12.5.1
[11:45:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/resetpower/Library/Application%20Support/epherome/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[11:45:25] [main/INFO]: Found mod file badpackets-forge-0.2.0.jar of type MOD with provider {mods folder locator at /Users/resetpower/Library/Application Support/epherome/minecraft/mods}
[11:45:25] [main/INFO]: Found mod file FpsReducer2-forge-1.19.2-2.1.jar of type MOD with provider {mods folder locator at /Users/resetpower/Library/Application Support/epherome/minecraft/mods}
[11:45:25] [main/INFO]: Found mod file ModernUI-1.19.2-3.6.0.114-universal.jar of type MOD with provider {mods folder locator at /Users/resetpower/Library/Application Support/epherome/minecraft/mods}
[11:45:25] [main/INFO]: Found mod file wthit-forge-5.12.0.jar of type MOD with provider {mods folder locator at /Users/resetpower/Library/Application Support/epherome/minecraft/mods}
[11:45:25] [main/INFO]: Found mod file Xaeros_Minimap_22.14.1_Forge_1.19.1.jar of type MOD with provider {mods folder locator at /Users/resetpower/Library/Application Support/epherome/minecraft/mods}
[11:45:26] [main/WARN]: Mod file /Users/resetpower/Library/Application Support/epherome/minecraft/libraries/net/minecraftforge/fmlcore/1.19.2-43.1.25/fmlcore-1.19.2-43.1.25.jar is missing mods.toml file
[11:45:26] [main/WARN]: Mod file /Users/resetpower/Library/Application Support/epherome/minecraft/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.1.25/javafmllanguage-1.19.2-43.1.25.jar is missing mods.toml file
[11:45:26] [main/WARN]: Mod file /Users/resetpower/Library/Application Support/epherome/minecraft/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.1.25/lowcodelanguage-1.19.2-43.1.25.jar is missing mods.toml file
[11:45:26] [main/WARN]: Mod file /Users/resetpower/Library/Application Support/epherome/minecraft/libraries/net/minecraftforge/mclanguage/1.19.2-43.1.25/mclanguage-1.19.2-43.1.25.jar is missing mods.toml file
[11:45:26] [main/INFO]: Found mod file fmlcore-1.19.2-43.1.25.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: Found mod file mclanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: Found mod file forge-1.19.2-43.1.25-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55e7a35c
[11:45:26] [main/INFO]: No dependencies to load found. Skipping!
[11:45:27] [main/INFO]: Compatibility level set to JAVA_17
[11:45:27] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.19.2-forge-43.1.25, --gameDir, /Users/resetpower/Library/Application Support/epherome/minecraft, --assetsDir, /Users/resetpower/Library/Application Support/epherome/minecraft/assets, --uuid, d9876a2d14694b86859d902f267067d6, --username, ResetPower, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3.222, --width, 854, --height, 480]
[11:45:27] [main/INFO]: OptiFine was NOT detected.
[11:45:27] [main/INFO]: OptiFabric was NOT detected.
[11:45:27] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[11:45:27] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[11:45:30] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[11:45:32] [Render thread/WARN]: Assets URL 'union:/Users/resetpower/Library/Application%20Support/epherome/minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23151!/assets/.mcassetsroot' uses unexpected schema
[11:45:32] [Render thread/WARN]: Assets URL 'union:/Users/resetpower/Library/Application%20Support/epherome/minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23151!/data/.mcassetsroot' uses unexpected schema
[11:45:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:45:33] [Render thread/INFO]: Setting user: ResetPower
[11:45:33] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[11:45:33] [Render thread/INFO]: OpenGL library: /usr/local/Cellar/mesa/22.1.7_1/lib/libGL.1.dylib
[11:45:34] [Render thread/INFO]: Promoted to OpenGL 4.1 Core Profile
```

**Comment by BloCamLimb** [comment]
At least from the log, the highest OpenGL is still 4.1, so there's no benefit in switching to Mesa.

**Comment by ResetPower** [comment]
can't get any info about it on google
too bad

**Comment by ResetPower** [comment]
maybe i should play minecraft on virtual machine 😫😓

**Comment by BloCamLimb** [comment]
Would you like to try version [1.19.2-3.7.0.0-RC1](https://github.com/BloCamLimb/ModernUI-MC/releases/tag/v3.7.0)? We have a complete compatibility for OpenGL 3.3, but there were reported rendering glitches on mac.

**Comment by BloCamLimb** [comment]
I would say there are no issues with Modern UI 3.7 on macOS.
