### ISSUE TITLE
[Bug] mods dependencies cause startup crashdown

### ISSUE THREAD

**Issue by kikbi** [BloCamLimb/ModernUI#142]
**Describe the bug**
I add some mods to 1.19.2 version. I knew there is some dependencies required. 
It looks like this.
![image](https://user-images.githubusercontent.com/29965471/222942795-886a3c63-8187-4d2e-9cd7-1ef5becfba57.png)

when I enable ModernUI, game crashed when start up. And there is no tips as pic shown above.
I knew what causes the crashdown. So I must disable ModernUI when I add some mods. But this is not very friendly to non-programmers.

The startup log is as follows:

[13:12:52] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'codechickenlib', Requested by: 'enderstorage', Expected range: '[4.3.0,5.0.0)', Actual version: '[MISSING]'
	Mod ID: 'titanium', Requested by: 'industrialforegoing', Expected range: '[3.5.8,)', Actual version: '[MISSING]'
[13:12:53] [main/ERROR]: Mixin config dynamiclightsreforged.mixins.json does not specify "minVersion" property
[13:12:53] [main/INFO]: Compatibility level set to JAVA_17
[13:12:53] [main/ERROR]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property

...skip

[13:13:01] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §eenderstorage§r requires §6codechickenlib§r §o4.3.0 or above, and below 5.0.0§r
§7Currently, §6codechickenlib§r§7 is §o§nnot installed
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.19.2-43.2.6.jar%23242!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:99) ~[fmlcore-1.19.2-43.2.6.jar%23242!/:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:131) ~[fmlcore-1.19.2-43.2.6.jar%23242!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:91) ~[forge-1.19.2-43.2.6-universal.jar%23246!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.2.6-universal.jar%23246!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:91) ~[forge-1.19.2-43.2.6-universal.jar%23246!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:468) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.6.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[13:13:01] [Render thread/WARN]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[13:13:01] [Render thread/INFO]: Loaded text layout engine, res level: 2.0, locale: zh_CN, layout RTL: false
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[13:13:01] [Render thread/INFO]: Hardware information:
[13:13:01] [Render thread/INFO]: CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700F
[13:13:01] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 2060/PCIe/SSE2 (Supports OpenGL 4.6.0 NVIDIA 526.86)
[13:13:01] [Render thread/INFO]: OS: Windows 10 (10.0)
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$ColorResolvers to a broken mod state
[13:13:01] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterItemDecorationsEvent to a broken mod state
[13:13:01] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:13:01] [Render thread/INFO]: Reloading ResourceManager: Default, Minecraft-Mod-Language-Modpack-1-18T1-19-1o2.zip
[13:13:01] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[13:13:01] [Worker-Main-15/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:01] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:01] [Worker-Main-7/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-2/INFO]: Scanned emoji map size: 0
[13:13:03] [Worker-Main-2/INFO]: Failed to load emoji data
java.io.FileNotFoundException: modernui:emoji_data.json
	at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215597_(ResourceProvider.java:28) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?]
	at icyllis.modernui.textmc.TextLayoutEngine.loadShortcodes(TextLayoutEngine.java:550) ~[ModernUI-1.19.2-3.6.3.117-universal.jar%23226!/:1.19.2-3.6.3.117]
	at icyllis.modernui.textmc.TextLayoutEngine.lambda$reload$1(TextLayoutEngine.java:403) ~[ModernUI-1.19.2-3.6.3.117-universal.jar%23226!/:1.19.2-3.6.3.117]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[13:13:03] [Worker-Main-2/INFO]: Scanned emoji shortcodes: 0, mismatched: 0
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:13:03] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state

**Environment**
 - Mod Version:3.6.3.117
 - Forge Version:43.2.6
 - Other Mods: oculus-mc1.19.2-1.2.8a/rubidium-0.6.2/rubidium_extras-1.19.2_v1.3.2

**Comment by BloCamLimb** [comment]
This is known and will be improved.

**Comment by BloCamLimb** [comment]
This issue was "fixed" in version 3.7.0, however, other mod errors may still cause Modern UI startup crash. As Modern UI startup requires some loading stages that may not be managed by Forge Mod Loader. There's no perfect solution to this issue, it's wise to check the `/logs/debug.log`.

This is not a bug.
