### ISSUE TITLE
[Bug] Crashes on dedicated server

### ISSUE THREAD

**Issue by sandalle** [BloCamLimb/ModernUI#155]
**Describe the bug**
Crashes on dedicated server (should be skipped if not needed on server, which https://www.curseforge.com/minecraft/mc-mods/modern-ui FAQ mentions, but we want modlists to match between client and server).

**To Reproduce**
1. Setup Dedicated server (Linux, no GUI, Java 18 for mine)
2. Use same mods/ folder for both client and server (this is how most modpacks have setup for over a decade)
3. Server version crashes

**Expected behavior**
If the mod shouldn't run on a server, should check for DEDICATED_SERVER and skip loading, or only load the parts essential for a client to talk to the server.

**Screenshots**
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWWindowCloseCallbackI
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWWindowCloseCallbackI
        at TRANSFORMER/modernui@3.7.0.5/icyllis.modernui.mc.forge.ModernUIForge.getBootstrapLevel(ModernUIForge.java:197)
        at TRANSFORMER/modernui@3.7.0.5/icyllis.modernui.mc.forge.MixinConfigPlugin.onLoad(MixinConfigPlugin.java:35)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:707)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:633)
        at java.base/java.lang.Class.forName(Class.java:577)
        at java.base/java.lang.Class.forName(Class.java:552)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.35/net.minecraftforge.fml.loading.ImmediateWindowHandler$DummyProvider.lambda$updateModuleReads$1(ImmediateWindowHandler.java:145)
        at java.base/java.util.Optional.map(Optional.java:260)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.35/net.minecraftforge.fml.loading.ImmediateWindowHandler$DummyProvider.updateModuleReads(ImmediateWindowHandler.java:145)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.35/net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.35/net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.35/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWWindowCloseCallbackI
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 36 more
```

**Environment**
 - Mod Version: 1.20.1-3.7.0.5-universal
 - Forge Version: 1.20.1-47.0.35
 - Operating System: Linux
 - Graphics Card: Advanced Micro Devices, Inc. [AMD/ATI] ES1000 (rev 02)
 - Other Mods: https://github.com/sandalle/nst-trailsandtales/blob/main/README.md

**Comment by BloCamLimb** [comment]
Done
