### ISSUE TITLE
[Bug] 在安卓平台使用导致崩溃 caused crash while being used on Android platform

### ISSUE THREAD

**Issue by Hongquan-Fu** [BloCamLimb/ModernUI#175]
**Describe the bug**
在安卓平台使用此mod后游戏崩溃
caused crash while being used on Android platform
**To Reproduce**
注：启动器是FCL 1.07         The launcher is Fold Craft Laumcher 1.07
以下是日志 here show the crash report below:
---- Minecraft Crash Report ----
```
// I feel sad now :(

Time: 2023/9/21 8:02P.M.
Description: Initializing game

java.lang.RuntimeException: OpenGL 3.2 core profile is unavailable
	at icyllis.modernui.graphics.opengl.GLCore.initialize(GLCore.java:178) ~[ModernUI-1.18.2-3.5.4.113-universal.jar%2348!/:1.18.2-3.5.4.113] {re:mixin,re:classloading}
	at icyllis.modernui.core.Core.initOpenGL(Core.java:271) ~[ModernUI-1.18.2-3.5.4.113-universal.jar%2348!/:1.18.2-3.5.4.113] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.handler$zzf000$onInitRenderer(RenderSystem.java:1485) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinRenderSystem,pl:mixin:APP:mixins.modernui-textmc.json:MixinRenderSystem,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69580_(RenderSystem.java:833) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinRenderSystem,pl:mixin:APP:mixins.modernui-textmc.json:MixinRenderSystem,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:453) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2319!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at icyllis.modernui.graphics.opengl.GLCore.initialize(GLCore.java:178) ~[ModernUI-1.18.2-3.5.4.113-universal.jar%2348!/:1.18.2-3.5.4.113] {re:mixin,re:classloading}
	at icyllis.modernui.core.Core.initOpenGL(Core.java:271) ~[ModernUI-1.18.2-3.5.4.113-universal.jar%2348!/:1.18.2-3.5.4.113] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.handler$zzf000$onInitRenderer(RenderSystem.java:1485) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinRenderSystem,pl:mixin:APP:mixins.modernui-textmc.json:MixinRenderSystem,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69580_(RenderSystem.java:833) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.modernui-forge.json:MixinRenderSystem,pl:mixin:APP:mixins.modernui-textmc.json:MixinRenderSystem,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:453) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2349!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2319!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version 4.14.180-perf-gfa6d44ac9278
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 464159824 bytes (442 MiB) / 1107296256 bytes (1056 MiB) up to 1442840576 bytes (1376 MiB)
	CPUs: 8
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 14 (aarch64)
	Identifier: 0x51 Family 8 Model 0x804 Stepping r0xdp14
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6846.90
	Virtual memory used (MB): 6760.01
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2008.77
	JVM Flags: 10 total; -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Adreno (TM) 640 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 14 (aarch64)
```
**
**Expected behavior**
caused crash （could because of the difference between openGL3.2 and openGL ES 3.2)

**Environment**
 - Mod Version:3.5.4.113 (however the latest version could also cause crush with the same report)
 - Forge Version:40.2.9
 - Operating System:Android 13
 - Graphics Card:Adreno 640（with the Snapdragon 860）
 - Other Mods:none ，only forge and ModernUI are installed

**Comment by BloCamLimb** [comment]
You should use Zink driver instead of gl4es.
