### ISSUE TITLE
[Bug] Mod Menu - Mod Icon Broken

### ISSUE THREAD

**Issue by EvanHsieh0415** [BloCamLimb/ModernUI#182]
**Describe the bug**
Mod icon is broken

**To Reproduce**
1. Go to mod menu
2. See error

**Expected behavior**
```java
[10:35:17] [Render thread/ERROR]: Mod icon must be a square for icon source modernui: modernui_logo.png
java.lang.IllegalStateException: Must be square icon
	at org.apache.commons.lang3.Validate.validState(Validate.java:816) ~[commons-lang3-3.12.0.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:36) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:161) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.getIconTexture(ModListEntry.java:130) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:59) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:241) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:227) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:285) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[10:35:17] [Render thread/WARN]: Warning! Mod modernui has a broken icon, loading default icon
```

**Screenshots**
![圖片](https://github.com/BloCamLimb/ModernUI/assets/74277414/383ee00e-9090-4c19-a28e-ecc32742fa0e)

**Environment**
 - Mod Version: v3.8.2.4
 - Fabric Version: 0.14.23
 - Operating System: Windows 11
 - Graphics Card: Intel(R) UHD Graphics
 - Other Mods: ![圖片](https://github.com/BloCamLimb/ModernUI/assets/74277414/e3e5433a-8528-42ed-8af9-4bf6a0850706)

**Comment by BloCamLimb** [comment]
Done
