### ISSUE TITLE
[Bug] 在将MUI作为模组开发前置时，进行数据生成出现会导致报错

### ISSUE THREAD

**Issue by AW-CRK14** [BloCamLimb/ModernUI#206]
如题。版本为neoforge1.20.4，gradle配置中将MUI设置为了compileOnly与runtimeOnly，MUI版本为3.10.0，执行任务runData
报错内容如下：
```java
[11:15:54] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: modernui, class icyllis.modernui.mc.neoforge.ModernUIForge
java.lang.NullPointerException: Cannot read field "options" because the return value of "net.minecraft.client.Minecraft.getInstance()" is null
	at icyllis.modernui.mc.text.TextLayoutEngine.reload(TextLayoutEngine.java:414) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:mixin,re:classloading}
	at icyllis.modernui.mc.text.TextLayoutEngine.<init>(TextLayoutEngine.java:326) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:mixin,re:classloading}
	at icyllis.modernui.mc.FontResourceManager.getInstance(FontResourceManager.java:90) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:mixin,re:classloading}
	at icyllis.modernui.mc.neoforge.ModernUIForge$Client.<init>(ModernUIForge.java:130) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:classloading,pl:runtimedistcleaner:A}
	at icyllis.modernui.mc.neoforge.ModernUIForge$Loader.init(ModernUIForge.java:109) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:classloading}
	at icyllis.modernui.mc.neoforge.ModernUIForge.<init>(ModernUIForge.java:90) ~[modern-ui-352491-5040141.jar%23200!/:1.20.4-3.10.0.6] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:112) ~[language-java-2.0.7.jar%23197!/:2.0] {}
	at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:130) ~[core-2.0.7.jar%23194!/:2.0] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[11:15:54] [main/FATAL] [ne.ne.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
```

推测为MUI在加载阶段调用了Minecraft.getInstance()并执行了相关操作，但runData任务状态下此方法返回值为null导致报错。

**Comment by Quarri6343** [comment]
I can't do runData too

**Comment by BloCamLimb** [comment]
Fixed in https://github.com/BloCamLimb/ModernUI-MC/commit/8ebb6e74692608abbf4a1f835639d62081fd26eb
