### ISSUE TITLE
Failed to register font - java.io.IOException: Can't read "x"

### ISSUE THREAD

**Issue by A5ho9999** [BloCamLimb/ModernUI#218]
**Describe the bug**
When trying to add a custom file through a resource pack it says it fails to register

```
[22:28:47] [Render thread/ERROR]: Failed to register font 'modpack:font\primitive.ttf'
java.io.IOException: Can't read modpack:font\primitive.ttf
	at java.awt.Font.checkFontFile(Font.java:1270) ~[?:?]
	at java.awt.Font.createFonts(Font.java:1032) ~[?:?]
	at icyllis.modernui.graphics.text.FontFamily.createFamilies(FontFamily.java:150) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.ModernUIClient.loadFonts(ModernUIClient.java:182) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.ModernUIClient.loadTypefaceInternal(ModernUIClient.java:362) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.ModernUIClient.onGetSelectedTypeface(ModernUIClient.java:307) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.ModernUI.getSelectedTypeface(ModernUI.java:432) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutEngine.getFontCollection(TextLayoutEngine.java:1192) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutProcessor.handleStyleRun(TextLayoutProcessor.java:832) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutProcessor.handleBidiRun(TextLayoutProcessor.java:740) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutProcessor.analyzeBidi(TextLayoutProcessor.java:618) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutProcessor.createNewLayout(TextLayoutProcessor.java:554) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutProcessor.createTextLayout(TextLayoutProcessor.java:423) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutEngine.lookupFormattedLayout(TextLayoutEngine.java:1046) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.TextLayoutEngine.lookupFormattedLayout(TextLayoutEngine.java:991) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.ModernStringSplitter.measureText(ModernStringSplitter.java:99) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.text.ModernStringSplitter.method_27488(ModernStringSplitter.java:67) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at net.minecraft.class_327.method_27525(class_327.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_51251(class_310.java:690) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:674) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
```

**To Reproduce**
1. Load game with mod and apply [modpack_resources.zip](https://github.com/user-attachments/files/15766572/modpack_resources.zip)
2. Set Config to use custom font "modpack:font/primitive.ttf"
3. Restart game

**Expected behavior**
Load the custom font

**Environment**
 - Mod Version: 3.10.1.4
 - Fabric Version: 0.92.2+1.20.1 (Loader 0.15.11)
 - Operating System: Windows
 - Other Mods: Mod Menu

**Comment by BloCamLimb** [comment]
Registered font families include:
1. OS builtin fonts.
1. Font files in fontRegistrationList.
1. Font files in '/resourcepacks' directory.
1. Font files under 'modernui:font' in resource packs.

Font registration list is a set of additional font files (or directories) *on file system* to register. It is not recommended to put fonts in a resource pack, because those files will be extracted into a temporary directory. But if you do it, only ones in `modernui:font/` will load.

**Comment by A5ho9999** [comment]
Yes it does load when in `modernui:font/` thank you,
