### ISSUE TITLE
[Bug] [MC 1.20.1] [Fabric] Intermitten crashes during gameplay.

### ISSUE THREAD

**Issue by Steven-OConnell** [BloCamLimb/ModernUI#227]
This is being reported on behalf of someone else.

Intermittent crashes during regular game-play.
The user has experienced similar crashes multiple times before simply while walking around or building.

Crash log shows the following @line 5861
`net.minecraft.class_2973: Invalid shaders/post/blur_fast.json (fabric) targets[0]: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT`

Full Error:
`net.minecraft.class_2973: Invalid shaders/post/blur_fast.json (fabric) targets[0]: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1256(class_279.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3168(class_757.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.callLoadEffect(class_757.java) ~[client-intermediary.jar:?]
	at icyllis.modernui.mc.fabric.MuiFabricApi.loadEffect(MuiFabricApi.java:83) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at icyllis.modernui.mc.BlurHandler.drawScreenBackground(BlurHandler.java:279) ~[ModernUI-Fabric-1.20.1-3.10.1.4-universal.jar:?]
	at net.minecraft.class_437.redirect$fcj000$modernui$renderBackgroundInWorld(class_437.java:700) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25420(class_437.java:332) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.11-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
	at net.minecraft.class_276.method_1239(class_276.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_276.method_1231(class_276.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_276.method_22596(class_276.java:70) ~[client-intermediary.jar:?]
	at net.minecraft.class_276.method_1234(class_276.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_6367.<init>(class_6367.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1261(class_279.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1265(class_279.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1256(class_279.java:71) ~[client-intermediary.jar:?]
	... 16 more
`

Log: 
[latest.log](https://github.com/user-attachments/files/16419784/latest.log)

MC - 1.20.1
Fabric - 0.15.11
OS - Windows 10
GPU - RX 7900XT
Driver ver - 31.0.24027.1012
Installed Mods: 
[~ModList.xlsx](https://github.com/user-attachments/files/16419770/ModList.xlsx)

**Comment by BloCamLimb** [comment]
It feels like a sort of failure on texture creation, I'm not sure if it's related to other mods. But I will try to improve this in the upcoming version.

**Comment by Steven-OConnell** [comment]
Aright thanks. 👍

**Comment by BloCamLimb** [comment]
Improved in https://github.com/BloCamLimb/ModernUI-MC/commit/e6b5f28d765bb225e10bf32722ce9869467d5560

**Comment by BloCamLimb** [comment]
Try out 3.11
