### ISSUE TITLE
[Bug] Outdated Java version

### ISSUE THREAD

**Issue by Traktool** [BloCamLimb/ModernUI#4]
**Describe the bug**
I'm on Java 1.8.251, so I'm using a 1.8.200+ version of Java, but the mod said that I'm on an outdated version

**To Reproduce**
Install Java 1.8.251, Forge 31.1.46, mod version 1.4.2.36 and launch

**Expected behavior**

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/22771674/79631915-5ae2aa80-815c-11ea-9b47-f46bd1ea1872.png)

**Versions you are on**
 - Mod Version: 1.4.2.36
 - Forge Version: 31.1.46

**Comment by BloCamLimb** [comment]
There's a log in debug.info tells your java version, search with [ModernUI/MAIN]

**Comment by Traktool** [comment]
[18avr.2020 10:02:56.474] [modloading-worker-3/FATAL] [ModernUI/MAIN]: You're using java 1.8.0_51 which is an outdated java version, please update it to java 1.8.0_200 or above
java.lang.RuntimeException: Outdated java version found, please update it to java 1.8.0_200 or above
	at icyllis.modernui.system.ModernUI.<init>(ModernUI.java:48) ~[?:1.15.2-1.4.2.36-universal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2236/141458554.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2235/656274624.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2235/656274624.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2349/974067570.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by BloCamLimb** [comment]
yp, you are using 1.8.0_51, check 
![image](https://user-images.githubusercontent.com/14106648/79632518-694bb900-8192-11ea-96f3-40346d79905d.png)

**Comment by Traktool** [comment]
Oh, it's the Java installed by default with Minecraft ..
Why this fucking launcher doesn't take the updated version we have installed ?!
All works fine now, thank you

**Comment by BloCamLimb** [comment]
Because this version that mojang has been using,
