### ISSUE TITLE
[Bug] Using \ instead of / for path in config causes crash

### ISSUE THREAD

**Issue by Bopler** [BloCamLimb/ModernUI#40]
**Describe the bug**
Using back slashes \ instead of forward slashes / in preferredFont config causes crash on startup.
FYI, Windows uses back slash when using copy as path.

**To Reproduce**
1. Open config
2. Use backslash in perferredFont   E.G "D:\Downloads\fontin_pc\Fontin-Bold.otf"
3. Save
4. Open game

**Expected behavior**
Game launches

**Screenshots**
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:60) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

```

**Environment**
 - Mod Version: 2.3.4.73
 - Forge Version: 35.1.36
 - Operating System: Windows 10 20H2
 - Graphics Card: RTX 2070 Super
 - Mods: 
> AppleSkin-mc1.16.2-forge-1.0.14.jar
> jei-1.16.4-7.6.1.65.jar
> ModernUI-1.16.4-2.3.4.73-universal.jar
> MouseTweaks-2.13-mc1.16.2.jar
> nicephore-1.16.x-1.3.1.jar
> OptiForge-MC1.16.4-0.4.5.jar
> preview_OptiFine_1.16.4_HD_U_G6_pre10.jar
> theoneprobe-1.16-3.0.7.jar

**Comment by BloCamLimb** [comment]
be49eeac88cdf24e090777af43fa04becf7c03b7 You must input "\\\\" rather than "\\" visually, it is an escape character.
