### ISSUE TITLE
[Bug] Untitled

### ISSUE THREAD

**Issue by smalllbuddy** [BloCamLimb/ModernUI#51]
This mod crashes when paired with Wolves with Armor - Forge
I have absolutely no idea but if it's an easy fix or there's anything I can do, please lmk!

Log:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/30/21 9:12 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: wolveswitharmor:leather_wolf_armor
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.handler$zbj000$createDefault(ItemColors.java:534) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:wolveswitharmor.mixins.json:ItemColorsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:wolveswitharmor.mixins.json:ItemColorsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.37.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/1054477035.call(Unknown Source) [forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.handler$zbj000$createDefault(ItemColors.java:534) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:wolveswitharmor.mixins.json:ItemColorsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:wolveswitharmor.mixins.json:ItemColorsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.37.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/1054477035.call(Unknown Source) [forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5254759896 bytes (5011 MB) / 6039797760 bytes (5760 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		TreeChop-1.16.4-0.12.2.jar                        |HT's TreeChop                 |treechop                      |0.12.2              |CREATE_REG|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|NOSIGNATURE
		Camels-1.16.4-1.0.0.jar                           |Camels Mod                    |camels                        |1.0.0               |CREATE_REG|NOSIGNATURE
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |CREATE_REG|NOSIGNATURE
		autorun-1.16.4-1.1.0.jar                          |Auto-Sprint                   |autorun                       |1.16.4-1.1.0        |CREATE_REG|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |CREATE_REG|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |CREATE_REG|NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |CREATE_REG|NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |CREATE_REG|NOSIGNATURE
		extcaves-2.4.jar                                  |Extended Caves                |extcaves                      |2.4                 |CREATE_REG|NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |CREATE_REG|NOSIGNATURE
		fishingreal-1.16.3-1.0.0.jar                      |Fishing Real                  |fishingreal                   |1.0.0               |CREATE_REG|NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |CREATE_REG|NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |CREATE_REG|NOSIGNATURE
		goblintraders-1.2.2-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.2.2               |CREATE_REG|NOSIGNATURE
		upgrade_aquatic-1.16.4-3.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.0               |CREATE_REG|NOSIGNATURE
		SMATM-1.16.4-1.7.2.jar                            |Spook's More Armor & Tools Mod|smaatm                        |1.16.4-1.7.2        |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |CREATE_REG|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |CREATE_REG|NOSIGNATURE
		Xaeros_Minimap_21.1.1_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.1.1              |CREATE_REG|NOSIGNATURE
		EnhancedVisuals_v1.3.24_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |CREATE_REG|NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |CREATE_REG|NOSIGNATURE
		alexsmobs-1.5.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.0               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |CREATE_REG|NOSIGNATURE
		backpacked-1.7.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.0               |CREATE_REG|NOSIGNATURE
		BasicNetherOres-1.16.4-5.4.0.jar                  |Basic Nether Ores             |bno                           |5.4.0               |CREATE_REG|NOSIGNATURE
		usefulhats-1.9.3-1.16.2+.jar                      |Useful Hats                   |usefulhats                    |1.9.3-1.16.2+       |CREATE_REG|NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |CREATE_REG|NOSIGNATURE
		wolveswitharmor-1.1.0-1.16.2 (1).jar              |Wolves With Armor             |wolveswitharmor               |1.1.0               |CREATE_REG|NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |CREATE_REG|d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guardvillagers-1.16.4-1.1.8.jar                   |Guard Villagers               |guardvillagers                |1.1.8               |CREATE_REG|NOSIGNATURE
		ModernUI-1.16.4-2.3.0.69-universal.jar            |Modern UI                     |modernui                      |2.3.0.69            |ERROR     |72:da:aa:fa:02:98:8b:71:b7:c5:ce:aa:0f:0d:cb:a3:ac:4b:97:d4:bc:fa:58:e6:98:e1:2e:ca:f4:61:a2:b0
		BackTools-1.16.3-10.0.0.jar                       |Back Tools                    |backtools                     |10.0.0              |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |CREATE_REG|NOSIGNATURE
		immersive-portals-0.14-mc1.16.4-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |CREATE_REG|NOSIGNATURE
		mysticalworld-1.16.4-0.3.1.7.jar                  |Mystical World                |mysticalworld                 |1.16.4-0.3.1.7      |CREATE_REG|NOSIGNATURE
		firstaid-1.9.5.jar                                |First Aid                     |firstaid                      |1.9.5               |CREATE_REG|NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-302.jar                                |Quark                         |quark                         |r2.4-302            |CREATE_REG|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1           |CREATE_REG|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |CREATE_REG|NOSIGNATURE
		SubWild-1.16.5-1.1.2.jar                          |Subterranean Wilderness       |subwild                       |1.1.2               |CREATE_REG|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.8.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.8      |CREATE_REG|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |CREATE_REG|NOSIGNATURE
		xptome-1.16.4-v2.0.1.jar                          |XP Tome                       |xpbook                        |v2.0.1              |CREATE_REG|NOSIGNATURE
	Crash Report UUID: d7b57c77-1c42-4d6e-991d-dc668feba56a
	Launched Version: 1.16.4-forge-35.1.37
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.16.4_HD_U_G6
	OptiFine Build: 20210117-001622
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 Medium.zip
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by BloCamLimb** [comment]
A minimum of Java 1.8.0_271 is required to run the mod, Java 11.0.8 or higher is recommended, currently your version is 1.8.0_51

**Comment by BloCamLimb** [comment]
some modders may not follow the standards, so you just saw this crash rather than an error prompt in GUI.
