### ISSUE TITLE
[Bug] Incompatible with CurseForge Launcher Modpacks because of Java Version

### ISSUE THREAD

**Issue by Lauriichan** [BloCamLimb/ModernUI#81]
**Describe the bug**
ModernUI is unable to start because it is compiled in Java 11 which is not supported by CurseForge.

CurseForge always uses the Java Version that is bundled with Minecraft (which is Java 8) and doesn't add the required Java Version tag to the version.json of a instance profile.
Therefore it is not possible to start with a mod that requires Java 11 to run.

**Log**
Started without change of Java Version to 11 (Minecraft Log)
```
[23:07:19] [main/INFO]: ModLauncher running: args [--username, MitzichenLaurii, --version, forge-36.2.5, --gameDir, D:\Games\Minecraft\CurseForge\Instances\Sky Project, --assetsDir, D:\Games\Minecraft\CurseForge\Install\assets, --assetIndex, 1.16, --uuid, 42eac4837cb24836a856e3659961cbe7, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.5, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[23:07:19] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[23:07:19] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[23:07:19] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[23:07:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/Games/Minecraft/CurseForge/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[23:07:22] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[23:07:22] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[23:07:24] [main/INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[23:07:24] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.UnsupportedClassVersionError: icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName0(Native Method)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName(Class.java:348)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$442/1013364696.accept(Unknown Source)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[23:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

Started with change of Java Version to 11 (Minecraft Launcher Log)
```
[Info: 2021-09-25 21:23:18.2641992: GameCallbacks.cpp(162)] Launcher/launcher (main) Info Checking installations.
[Info: 2021-09-25 21:23:18.2653816: GameCallbacks.cpp(162)] Launcher/launcher (main) Info Minecraft client forge-36.2.5 is ready to start.
[Info: 2021-09-25 21:23:18.2654632: GameController.cpp(453)] Starting game with token 4
[Info: 2021-09-25 21:23:18.2654978: GameCallbacks.cpp(162)] Launcher/launcher (main) Info Starting!
[Info: 2021-09-25 21:23:18.2655451: GameCallbacks.cpp(162)] Launcher/launcher (main) Debug Nothing to download!
[Info: 2021-09-25 21:23:18.2656098: GameCallbacks.cpp(162)] Launcher/launcher (main) Debug Extracting 8 files!
[Info: 2021-09-25 21:23:18.3666733: GameCallbacks.cpp(162)] Launcher/launcher (main) Info Using default game log configuration client-1.12.xml (outputs XML)
[Info: 2021-09-25 21:23:18.3667116: GameCallbacks.cpp(162)] Launcher/launcher (main) Debug Installing versions!
[Info: 2021-09-25 21:23:18.3670621: Process_Windows.cpp(33)] Creating process C:\...\javaw.exe
[Info: 2021-09-25 21:23:18.3674473: Process_Windows.cpp(102)] Starting process C:\...\javaw.exe
[Info: 2021-09-25 21:23:18.3719883: Process_Windows.cpp(153)] Read thread is 20856
[Info: 2021-09-25 21:23:18.5169233: ClientStarter.cpp(976)] Java Runtime Version : 11.0.9
[Info: 2021-09-25 21:23:18.5169290: Process_Windows.cpp(283)] Finish any outstanding read/writes to the stdout stream
[Info: 2021-09-25 21:23:18.5169756: ClientStarter.cpp(977)] Java Runtime Version Required : 8
[Error: 2021-09-25 21:23:18.5170122: ClientStarter.cpp(994)] Java Runtime mismatch! Please switch java runtime settings to use bundled jre.
[Info: 2021-09-25 21:23:18.5170722: Process_Windows.cpp(76)] Exiting process C:\...\javaw.exe
[Info: 2021-09-25 21:23:18.5171204: Process_Windows.cpp(80)] Joining stdout thread
[Info: 2021-09-25 21:23:18.5172007: Process_Windows.cpp(86)] Joined!
[Error: 2021-09-25 21:23:18.5172782: ClientStarter.cpp(1058)] Java Check Versions mismatch
```

**Possible Fix**
Set the target Java version to 8 so that gradlew compiles to Java 8 Bytecode instead of Java 11 Bytecode.

**To Reproduce**
1. Create a Modpack on CurseForge for 1.16.5
2. Install the ModernUI Mod
3. Try to start the game
4. See that it crashed

**Expected behavior**
Minecraft should start normally

**Screenshots**
Started without change of Java Version to 11
![image](https://user-images.githubusercontent.com/41839265/134786012-f98b444c-aaa2-4550-a504-e987b5725c81.png)

Started with change of Java Version to  11
![image](https://user-images.githubusercontent.com/41839265/134786106-76de89ec-4578-4dfc-aafe-20a2d94c3317.png)

**Environment**
 - Mod Version: 1.16.5-2.6.3.91
 - Forge Version: 36.2.5
 - Operating System: Windows 10
 - Java Version: 8; 11; 14; 16

**Comment by BloCamLimb** [comment]
It's really not something I can do. I dropped Java 8 since my next target is 1.17, and there're so many shortcomings in Java 8. Try MultiMC launcher.
